#depends_on: 
  # -...
  #pour lancer les choses dans l'ordre
  
version: '3.7'

services:
  
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ..:/usr/src/TMDB/
    networks:
      - database_net
    #command : tail -f /dev/null
    depends_on: 
      - database
  
  database:
    image: mysql:latest
    env_file:
      - .env
    networks:
      - database_net
    ports:
      - 3307:3307
    volumes:
      - database_data:/var/lib/mysql
      - ../init-db:/docker-entrypoint-initdb.d
    command: --default_authentication_plugin=mysql_native_password
    healthcheck:  # teste que le port 3306 est prêt -> la bdd est chargée
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      interval: 10s
      retries: 10
  
  adminer:
    image: dehy/adminer
    networks:
      - database_net
    ports:
      - 8080:80

networks:
  database_net:
    driver: bridge

volumes:
  database_data: